imports:
    - { resource: @NetworkingInitCmsBundle/Resources/config/cms/security_config.yml }
    - { resource: @NetworkingInitCmsBundle/Resources/config/cms/sonata_admin.yml }
    - { resource: @NetworkingInitCmsBundle/Resources/config/cms/sonata_doctrine_admin.yml }
    - { resource: @NetworkingInitCmsBundle/Resources/config/cms/sonata_block.yml }
    - { resource: @NetworkingInitCmsBundle/Resources/config/cms/sonata_formatter.yml }
    - { resource: @NetworkingInitCmsBundle/Resources/config/cms/stof_doctrine_extensions.yml }
    - { resource: @NetworkingInitCmsBundle/Resources/config/cms/symfony_cmf_routing_extra.yml }
    - { resource: @NetworkingInitCmsBundle/Resources/config/cms/mopa_bootstrap.yml }
    - { resource: @NetworkingInitCmsBundle/Resources/config/cms/sonata_media.yml }
    - { resource: @NetworkingInitCmsBundle/Resources/config/cms/jms_serializer.yml }
    - { resource: @NetworkingInitCmsBundle/Resources/config/cms/lexik_translation.yml }
    - { resource: @NetworkingInitCmsBundle/Resources/config/cms/ibrows_sonata_translation.yml }
    - { resource: @NetworkingInitCmsBundle/Resources/config/cms/ivory_ck_editor.yml }