fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb'
    firewall_name:  main
    user_class:     Networking\InitCmsBundle\Entity\User
    group:
        group_class: Networking\InitCmsBundle\Entity\Group
    from_email:
            address:        webmaster@example.com
            sender_name:    net working Team