imports:
    - { resource: "@NetworkingInitCmsBundle/Resources/config/cms/doctrine.yaml" }
    - { resource: "@NetworkingInitCmsBundle/Resources/config/cms/fos_ck_editor.yaml" }
    - { resource: "@NetworkingInitCmsBundle/Resources/config/cms/fos_user.yaml" }
    - { resource: "@NetworkingInitCmsBundle/Resources/config/cms/jms_serializer.yaml" }
    - { resource: "@NetworkingInitCmsBundle/Resources/config/cms/lexik_translation.yaml" }
    - { resource: "@NetworkingInitCmsBundle/Resources/config/cms/mopa_bootstrap.yaml" }
    - { resource: "@NetworkingInitCmsBundle/Resources/config/cms/oneup_flysystem.yaml" }
    - { resource: "@NetworkingInitCmsBundle/Resources/config/cms/oneup_uploader.yaml" }
    - { resource: "@NetworkingInitCmsBundle/Resources/config/cms/security.yaml" }
    - { resource: "@NetworkingInitCmsBundle/Resources/config/cms/sonata_admin.yaml" }
    - { resource: "@NetworkingInitCmsBundle/Resources/config/cms/sonata_block.yaml" }
    - { resource: "@NetworkingInitCmsBundle/Resources/config/cms/sonata_core.yaml" }
    - { resource: "@NetworkingInitCmsBundle/Resources/config/cms/sonata_doctrine_admin.yaml" }
    - { resource: "@NetworkingInitCmsBundle/Resources/config/cms/sonata_media.yaml" }
    - { resource: "@NetworkingInitCmsBundle/Resources/config/cms/sonata_notification.yaml" }
    - { resource: "@NetworkingInitCmsBundle/Resources/config/cms/sonata_user.yaml" }
    - { resource: "@NetworkingInitCmsBundle/Resources/config/cms/stof_doctrine_extensions.yaml" }
    - { resource: "@NetworkingInitCmsBundle/Resources/config/cms/symfony_cmf_routing_extra.yaml" }
