jms_serializer:
    visitors:
        xml:
            format_output: '%kernel.debug%'
    metadata:
        directories:
            NetworkingSonataMediaBundle:
                namespace_prefix: "Sonata\\MediaBundle"
                path: "@NetworkingInitCmsBundle/Resources/config/serializer"
            app:
                namespace_prefix: "App"
                path: "%kernel.project_dir%/config/serializer"