sonata_doctrine_orm_admin:
    templates:
        form: [ '@NetworkingInitCms/Form/form_admin_fields.html.twig' ]
        filter:
            - '@NetworkingInitCms/Form/form_admin_fields.html.twig'
        types:
            list:
                array:      '@NetworkingInitCms/CRUD/list_array.html.twig'
                boolean:    '@NetworkingInitCms/CRUD/list_boolean.html.twig'
                date:       '@NetworkingInitCms/CRUD/list_date.html.twig'
                time:       '@NetworkingInitCms/CRUD/list_time.html.twig'
                datetime:   '@NetworkingInitCms/CRUD/list_datetime.html.twig'
                text:       '@NetworkingInitCms/CRUD/list_string.html.twig'
                trans:      '@NetworkingInitCms/CRUD/list_trans.html.twig'
                string:     '@NetworkingInitCms/CRUD/list_string.html.twig'
                smallint:   '@NetworkingInitCms/CRUD/base_list_field.html.twig'
                bigint:     '@NetworkingInitCms/CRUD/base_list_field.html.twig'
                integer:    '@NetworkingInitCms/CRUD/base_list_field.html.twig'
                decimal:    '@NetworkingInitCms/CRUD/base_list_field.html.twig'
                identifier: '@NetworkingInitCms/CRUD/base_list_field.html.twig'

            show:
                array:      '@NetworkingInitCms/CRUD/show_array.html.twig'
                boolean:    '@NetworkingInitCms/CRUD/show_boolean.html.twig'
                date:       '@NetworkingInitCms/CRUD/show_date.html.twig'
                time:       '@NetworkingInitCms/CRUD/show_time.html.twig'
                datetime:   '@NetworkingInitCms/CRUD/show_datetime.html.twig'
                text:       '@NetworkingInitCms/CRUD/base_show_field.html.twig'
                trans:      '@NetworkingInitCms/CRUD/show_trans.html.twig'
                string:     '@NetworkingInitCms/CRUD/base_show_field.html.twig'
                smallint:   '@NetworkingInitCms/CRUD/base_show_field.html.twig'
                bigint:     '@NetworkingInitCms/CRUD/base_show_field.html.twig'
                integer:    '@NetworkingInitCms/CRUD/base_show_field.html.twig'
                decimal:    '@NetworkingInitCms/CRUD/base_show_field.html.twig'
                birthday:   '@NetworkingInitCms/CRUD/show_date.html.twig'
