Networking\InitCmsBundle\Entity\HelpText:
  type: entity
  table: help_text
  id:
    id:
      type: integer
      generator:
        strategy: AUTO

  fields:
    locale:
      type: string
      length: 6ÃŸ
    translationKey:
      type: string
      length: 255
      column: translation_key
    text:
      type: text
    title:
      type: string
      length: 255
      nullable: true
    isDeletable:
      type: boolean
      column: is_deletable

