Networking\InitCmsBundle\Entity\LayoutBlock:
  type: entity
  table: layout_block
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    name:
      type: string
      length: 255
      nullable: true
    zone:
      type: string
      length: 255
    classType:
      type: string
      length: 255
      column: class_type
    objectId:
      type: integer
      column: object_id
      nullable: true
    isActive:
      type: boolean
      column: is_active
    sortOrder:
      type: integer
      column: sort_order
      nullable: true
    createdAt:
      type: datetime
      column: created_at
    updatedAt:
      type: datetime
      column: updated_at
  lifecycleCallbacks:
    prePersist: [ prePersist ]
    preUpdate: [ preUpdate ]